In [1]:
import numpy as np

In [2]:
def gaussian_elimination_no_pivot(A, b):
    n = len(b)
    A = A.copy()
    b = b.copy()
    
    steps = []
    
    for i in range(n - 1):
        for j in range(i + 1, n):
            if A[i, i] == 0:
                raise ValueError("Division by zero in Gaussian elimination")

            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
            b[j] -= factor * b[i]
            
            steps.append((A.copy(), b.copy()))
    
    x = np.zeros_like(b)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]
        
    return x, steps

In [3]:
def gaussian_elimination_with_pivot(A, b):
    n = len(b)
    A = A.copy()
    b = b.copy()
    
    steps = []
    
    for i in range(n-1):
        max_row = np.argmax(np.abs(A[i:,i])) + i
        if A[max_row, i] == 0:
            raise ValueError("No unique solution exists")
        
        A[[i, max_row]] = A[[max_row, i]]
        b[[i, max_row]] = b[[max_row, i]]
        
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
            b[j] -= factor * b[i]
            
            steps.append((A.copy(), b.copy()))
            
    x = np.zeros_like(b)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]
        
    return x, steps

In [4]:
def display_solution(solution, title):
    print(f"\n{'=' * 50}")
    print(f"{title}")
    print(f"{'=' * 50}")
    for i , value in enumerate(solution):
        print(f"x[{i + 1}]) = {value:.3f}")
    print(f"\n{'=' * 50}")

In [5]:
def display_steps(steps, title):
    print(f"\n{'=' * 50}")
    print(f"{title}")
    print(f"{'=' * 50}")
    for i, (A_step, b_step) in enumerate(steps):
        print(f"Step {i + 1}")
        print("Matrix A:")
        print(np.array_str(A_step, precision=3, suppress_small=True))
        print("Vector b:")
        print(np.array_str(b_step, precision=3, suppress_small=True))
        print(f"{'-' * 50}")

In [6]:
A = np.array([
    [2, 1, -1, 3, 1],
    [-3, -1, 2, 1, 2],
    [1, 2, 1, -1, 4],
    [4, 3, 2, 1, 5],
    [2, -1, 3, 4, 6]
    ], dtype=float)

b = np.array([8, -11, -3, 18, 5], dtype=float)

In [7]:
try:
    x_no_pivot, steps_no_pivot = gaussian_elimination_no_pivot(A, b)
    display_steps(steps_no_pivot, title="Step without Pivoting")
    display_solution(x_no_pivot, title="Solution without Pivoting")
except ValueError as e:
    print("Error without pivoting:", e)

Error without pivoting: Division by zero in Gaussian elimination


In [8]:
x_with_pivot, steps_with_pivot = gaussian_elimination_with_pivot(A, b)
display_steps(steps_with_pivot, title="Step with Pivoting")
display_solution(x_with_pivot, title="Solution with Pivoting")


Step with Pivoting
Step 1
Matrix A:
[[ 4.    3.    2.    1.    5.  ]
 [ 0.    1.25  3.5   1.75  5.75]
 [ 1.    2.    1.   -1.    4.  ]
 [ 2.    1.   -1.    3.    1.  ]
 [ 2.   -1.    3.    4.    6.  ]]
Vector b:
[18.   2.5 -3.   8.   5. ]
--------------------------------------------------
Step 2
Matrix A:
[[ 4.    3.    2.    1.    5.  ]
 [ 0.    1.25  3.5   1.75  5.75]
 [ 0.    1.25  0.5  -1.25  2.75]
 [ 2.    1.   -1.    3.    1.  ]
 [ 2.   -1.    3.    4.    6.  ]]
Vector b:
[18.   2.5 -7.5  8.   5. ]
--------------------------------------------------
Step 3
Matrix A:
[[ 4.    3.    2.    1.    5.  ]
 [ 0.    1.25  3.5   1.75  5.75]
 [ 0.    1.25  0.5  -1.25  2.75]
 [ 0.   -0.5  -2.    2.5  -1.5 ]
 [ 2.   -1.    3.    4.    6.  ]]
Vector b:
[18.   2.5 -7.5 -1.   5. ]
--------------------------------------------------
Step 4
Matrix A:
[[ 4.    3.    2.    1.    5.  ]
 [ 0.    1.25  3.5   1.75  5.75]
 [ 0.    1.25  0.5  -1.25  2.75]
 [ 0.   -0.5  -2.    2.5  -1.5 ]
 [ 0.   -2.5   2. 