In [12]:
import numpy as np

In [13]:
def lu_decomposition_with_pivot(A):
    n = A.shape[0]
    P = np.eye(n)
    A = A.copy()
    
    steps = []
    
    for i in range(n - 1):
        max_row = np.argmax(np.abs(A[i:, i])) + i
        if A[max_row, i] == 0:
            raise ValueError("No unique solution exists")
        
        A[[i, max_row]] = A[[max_row, i]]
        P[[i, max_row]] = P[[max_row, i]]
    
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            
            A[j, i] = factor
            
            for k in range(i + 1, n):
                A[j, k] -= factor * A[i, k]
                
            steps.append((A.copy))
        
    return A, P, steps

In [14]:
def extract_lu(A_lu):
    n = A_lu.shape[0]
    L = np.eye(n)
    U = np.zeros_like(A_lu)
    
    for i in range(n):
        for j in range(n):
            if i > j:
                L[i, j] = A_lu[i, j]
            else:
                U[i, j] = A_lu[i, j]
                
    return L, U

In [15]:
def forward_substitution(L, b):
    n = len(b)
    D = np.zeros_like(b)
    
    for i in range(n):
        D[i] = b[i] - np.dot(L[i, :i], D[:i])
        
    return D

In [16]:
def backward_substitution(U, y):
    n = len(y)
    x = np.zeros_like(y)
    
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
        
    return x

since we have Main Dish, Drinks, Desserts as variable\
**Person 1**\
2 Main + 3 Drinks + 1 Desserts = 230 baht\
**Person 2**\
1 Main + 2 Drinks + 2 Desserts = 150 baht\
**Person 3**\
1 Main + 1 Drinks + 3 Desserts = 130 baht\
find cost per item

can write as

$\begin{bmatrix} 2 & 3 & 1 \\ 1 & 2 & 2 \\ 1 & 1 & 3 \end{bmatrix} \cdot \begin{bmatrix}  \textrm{Main} \\ \textrm{Drinks} \\ \textrm{Desserts} \end{bmatrix} = \begin{bmatrix} 230 \\ 150 \\ 130 \end{bmatrix}$

In [17]:
A = np.array([
    [2, 3, 1],
    [1, 2, 2],
    [1, 1, 3]
    ], dtype=float)

b = np.array([230, 150, 130], dtype=float)

LU decomposition of A

In [18]:
lu , permu, steps_pivot = lu_decomposition_with_pivot(A)

print(np.array_str(lu, precision=3, suppress_small=True))
print(np.array_str(permu, precision=3, suppress_small=True))

[[ 2.   3.   1. ]
 [ 0.5  0.5  1.5]
 [ 0.5 -1.   4. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Extract LU

In [19]:
L, U = extract_lu(lu)

print("\nLower Triangular Matrix L:")
print(np.array_str(L, precision=3, suppress_small=True))
print("\nUpper Triangular Matrix U:")
print(np.array_str(U, precision=3, suppress_small=True))
print("\nReconstructed Matrix L @ U:")
print(np.array_str(L @ U, precision=3, suppress_small=True))
print("\nPermuted Matrix P @ A:")
print(np.array_str(permu @ A, precision=3, suppress_small=True))


Lower Triangular Matrix L:
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.5 -1.   1. ]]

Upper Triangular Matrix U:
[[2.  3.  1. ]
 [0.  0.5 1.5]
 [0.  0.  4. ]]

Reconstructed Matrix L @ U:
[[2. 3. 1.]
 [1. 2. 2.]
 [1. 1. 3.]]

Permuted Matrix P @ A:
[[2. 3. 1.]
 [1. 2. 2.]
 [1. 1. 3.]]


Forward Substitution

In [20]:
D = forward_substitution(lu, b)
print(f"D = {np.array_str(D, precision=3, suppress_small=True)}")

D = [230.  35.  50.]


Backward Substitution

In [21]:
X = backward_substitution(lu, D)
print(f"x = {np.array_str(X, precision=3, suppress_small=True)}")

x = [60.  32.5 12.5]


**Result**

In [22]:
print(f"Main = {X[0]} bath")
print(f"Drinks = {X[1]} bath")
print(f"Desserts = {X[2]} bath")

Main = 60.0 bath
Drinks = 32.5 bath
Desserts = 12.5 bath
