In [69]:
import numpy as np

In [70]:
def lu_decomposition_with_pivot(A):
    n = A.shape[0]
    P = np.eye(n)
    A = A.copy()
    
    steps = []
    
    for i in range(n - 1):
        max_row = np.argmax(np.abs(A[i:, i])) + i
        if A[max_row, i] == 0:
            raise ValueError("No unique solution exists")
        
        A[[i, max_row]] = A[[max_row, i]]
        P[[i, max_row]] = P[[max_row, i]]
    
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            
            A[j, i] = factor
            
            for k in range(i + 1, n):
                A[j, k] -= factor * A[i, k]
                
            steps.append((A.copy))
        
    return A, P, steps

In [71]:
def extract_lu(A_lu):
    n = A_lu.shape[0]
    L = np.eye(n)
    U = np.zeros_like(A_lu)
    
    for i in range(n):
        for j in range(n):
            if i > j:
                L[i, j] = A_lu[i, j]
            else:
                U[i, j] = A_lu[i, j]
                
    return L, U

In [72]:
def forward_substitution(L, b):
    n = len(b)
    D = np.zeros_like(b)
    
    for i in range(n):
        D[i] = b[i] - np.dot(L[i, :i], D[:i])
        
    return D

In [73]:
def backward_substitution(U, y):
    n = len(y)
    x = np.zeros_like(y)
    
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
        
    return x

In [74]:
def display_solution(solution, title):
    print(f"\n{'=' * 50}")
    print(f"{title}")
    print(f"{'=' * 50}")
    for i , value in enumerate(solution):
        print(f"x[{i + 1}]) = {value:.3f}")
    print(f"\n{'=' * 50}")

In [75]:
def display_steps(steps, title):
    print(f"\n{'=' * 50}")
    print(f"{title}")
    print(f"{'=' * 50}")
    for i, (A_step, b_step) in enumerate(steps):
        print(f"Step {i + 1}")
        print("Matrix A:")
        print(np.array_str(A_step, precision=3, suppress_small=True))
        print("Vector b:")
        print(np.array_str(b_step, precision=3, suppress_small=True))
        print(f"{'-' * 50}")

since we have Main Dish, Drinks, Desserts as variable\
**Person 1**\
2 Main + 3 Drinks + 1 Desserts = 200 baht\
**Person 2**\
1 Main + 2 Drinks + 2 Desserts = 150 baht\
**Person 3**\
1 Main + 1 Drinks + 3 Desserts = 100 baht\
find cost per item

can write as

$\begin{bmatrix} 2 & 3 & 1 \\ 1 & 2 & 2 \\ 1 & 1 & 3 \end{bmatrix} \cdot \begin{bmatrix}  \textrm{Main} \\ \textrm{Drinks} \\ \textrm{Desserts} \end{bmatrix} = \begin{bmatrix} 200 \\ 150 \\ 100 \end{bmatrix}$

In [76]:
A = np.array([
    [2, 3, 1],
    [1, 2, 2],
    [1, 1, 3]
    ], dtype=float)

b = np.array([200, 150, 100], dtype=float)

LU decomposition of A

In [77]:
lu , permu, steps_pivot = lu_decomposition_with_pivot(A)

print(np.array_str(lu, precision=3, suppress_small=True))
print(np.array_str(permu, precision=3, suppress_small=True))

[[ 2.   3.   1. ]
 [ 0.5  0.5  1.5]
 [ 0.5 -1.   4. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Extract LU

In [78]:
L, U = extract_lu(lu)

print("\nLower Triangular Matrix L:")
print(np.array_str(L, precision=3, suppress_small=True))
print("\nUpper Triangular Matrix U:")
print(np.array_str(U, precision=3, suppress_small=True))
print("\nReconstructed Matrix L @ U:")
print(np.array_str(L @ U, precision=3, suppress_small=True))
print("\nPermuted Matrix P @ A:")
print(np.array_str(permu @ A, precision=3, suppress_small=True))


Lower Triangular Matrix L:
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.5 -1.   1. ]]

Upper Triangular Matrix U:
[[2.  3.  1. ]
 [0.  0.5 1.5]
 [0.  0.  4. ]]

Reconstructed Matrix L @ U:
[[2. 3. 1.]
 [1. 2. 2.]
 [1. 1. 3.]]

Permuted Matrix P @ A:
[[2. 3. 1.]
 [1. 2. 2.]
 [1. 1. 3.]]


Forward Substitution

In [79]:
D = forward_substitution(lu, b)
print(f"D = {np.array_str(D, precision=3, suppress_small=True)}")

D = [200.  50.  50.]


Backward Substitution

In [80]:
X = backward_substitution(lu, D)
print(f"x = {np.array_str(X, precision=3, suppress_small=True)}")

x = [ 0.  62.5 12.5]


**Result**

In [81]:
print(f"Main = {X[0]} bath")
print(f"Drinks = {X[1]} bath")
print(f"Desserts = {X[2]} bath")

Main = 0.0 bath
Drinks = 62.5 bath
Desserts = 12.5 bath
